### ISSUE TITLE
只能在oncreate方法里面生成吗？能不能指定方法里面生成，因为我的类继承父类后就没有再重写oncreate方法了。

### ISSUE THREAD

**Issue by xumugithub** [Joehaivo/RemoveButterKnife#2]

**Comment by ccccmmmz** [comment]
我fork的项目兼容了这种超类没继承情况 你可以试下 有问题可以联系我

**Comment by Joehaivo** [comment]
可以的, 最近工作较忙, 没有经历维护

**Comment by fanpeihua** [comment]
> 

hello 我直接试了你的 1.5.2 的jar，应该怎么指定方法呢？

**Comment by fanpeihua** [comment]
> 我fork的项目兼容了这种超类没继承情况 你可以试下 有问题可以联系我

hello 我直接试了你的 1.5.2 的jar，应该怎么指定方法呢？

**Comment by ccccmmmz** [comment]
> 
不用指定方法 直接使用 我用了匹配 兼容了

**Comment by fanpeihua** [comment]
> 

没能生效额，我的ButterKnife.bind(this); 写在 Activity继承的 BaseActivity 里的  onCreate() -> initSuperView() -> initContentLayout() 这个方法中。和层级较深有关么

**Comment by ccccmmmz** [comment]
> > 
> 
> 没能生效额，我的ButterKnife.bind(this); 写在 Activity继承的 BaseActivity 里的 onCreate() -> initSuperView() -> initContentLayout() 这个方法中。和层级较深有关么

如果可以的话你能给你的基类抽出个demo么 业务类不要 我试下

**Comment by fanpeihua** [comment]
> > > 
> > 
> > 
> > 没能生效额，我的ButterKnife.bind(this); 写在 Activity继承的 BaseActivity 里的 onCreate() -> initSuperView() -> initContentLayout() 这个方法中。和层级较深有关么
> 
> 如果可以的话你能给你的基类抽出个demo么 业务类不要 我试下

好的，精简以后大概是这样。
`public abstract class BaseAct extends AppCompatActivity  {
    public abstract int getResLayoutId();
 
    public abstract void loadViewData(@Nullable Bundle savedInstanceState);

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        
        super.onCreate(savedInstanceState);
        
        super.setContentView(R.layout.act_base);
        //初始化父类控件
        initSuperView(savedInstanceState);
    }


    private void initSuperView(@Nullable Bundle savedInstanceState) {
        initContentLayout();
      
        loadViewData(savedInstanceState);
    }

    public void initContentLayout() {
        if (getResLayoutId() == -1) {
            return;
        }
        View contentView = LayoutInflater.from(this).inflate(getResLayoutId(), null);
        if (contentView != null) {
            ViewGroup.LayoutParams layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            ButterKnife.bind(this);
        }
    }


    public <T extends View> T bingView(int id) {
        return (T) findViewById(id);
    }


}
`

**Comment by ccccmmmz** [comment]
> > > > 
> > > 
> > > 
> > > 没能生效额，我的ButterKnife.bind(this); 写在 Activity继承的 BaseActivity 里的 onCreate() -> initSuperView() -> initContentLayout() 这个方法中。和层级较深有关么
> > 
> > 
> > 如果可以的话你能给你的基类抽出个demo么 业务类不要 我试下
> 
> 好的，精简以后大概是这样。 `public abstract class BaseAct extends AppCompatActivity { public abstract int getResLayoutId();
> 
> ```
> public abstract void loadViewData(@Nullable Bundle savedInstanceState);
> 
> @Override
> protected void onCreate(@Nullable Bundle savedInstanceState) {
>     
>     super.onCreate(savedInstanceState);
>     
>     super.setContentView(R.layout.act_base);
>     //初始化父类控件
>     initSuperView(savedInstanceState);
> }
> 
> 
> private void initSuperView(@Nullable Bundle savedInstanceState) {
>     initContentLayout();
>   
>     loadViewData(savedInstanceState);
> }
> 
> public void initContentLayout() {
>     if (getResLayoutId() == -1) {
>         return;
>     }
>     View contentView = LayoutInflater.from(this).inflate(getResLayoutId(), null);
>     if (contentView != null) {
>         ViewGroup.LayoutParams layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
>         ButterKnife.bind(this);
>     }
> }
> 
> 
> public <T extends View> T bingView(int id) {
>     return (T) findViewById(id);
> }
> ```
> 
> } `

哥留个联系方式吧,我加您
