### ISSUE TITLE
Target type of a lambda conversion must be an interface

### ISSUE THREAD

**Issue by AreYReady** [Joehaivo/RemoveButterKnife#3]
使用class 不允许用 lamdba的形式
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/13625746/197728006-b6d9c72c-d75d-47cb-acbe-adf1a9e90fd2.png">

**Comment by ccccmmmz** [comment]
这个可以试用下我fork的,我跳过这种lambda的方式

**Comment by AreYReady** [comment]
嗯，我自己改了下，改成接口就可以了。。少了双击限定。使用另外的方式来实现双击限定
